server:
  port: 9898
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lilac_blog?CharacterEncoding=utf8&serviceTimezone=Asia/Shanghai
    username: root
    password: 757520
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB

  data:
    redis:
      host: localhost
      password: 757520
      port: 6379
      database: 0

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0

logging:
  level:
    com:
      sky:
        mapper: debug
        service: info
        controller: info

Blog:
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: ${ALIBABA_ACCESS_KEY_ID}
    access-key-secret: ${ALIBABA_ACCESS_KEY_SECRET}
    bucket-name: lilacs